import type { GameMeta } from './types';

export const GAMES: GameMeta[] = [
  { slug: 'highway-rush', title: 'Highway Rush', tagline: 'Dodge traffic at top speed', description: 'Race down a three-lane highway and weave through endless traffic. Switch lanes fast and survive as long as you can — the further you go, the faster it gets.', category: 'racing', icon: 'Car', accent: '#ef4444', difficulty: 'Medium', controls: ['Arrow Left / Right', 'A / D'], featured: true },
  { slug: 'parking-master', title: 'Parking Master', tagline: 'Squeeze into the perfect spot', description: 'Carefully guide your car into the highlighted parking bay without bumping into anything. Tight spaces, tight turns, tight time limit.', category: 'parking', icon: 'ParkingCircle', accent: '#3b82f6', difficulty: 'Hard', controls: ['Arrow Keys', 'Space to brake'], featured: true },
  { slug: 'drift-circle', title: 'Drift Circle', tagline: 'Hold the drift, stay on track', description: 'Keep your car drifting around a circular track. Stay inside the ring to build your combo — one slip and your run is over.', category: 'skill', icon: 'CircleDot', accent: '#f97316', difficulty: 'Hard', controls: ['Hold Space / Click'] },
  { slug: 'taxi-frenzy', title: 'Taxi Frenzy', tagline: 'Pick up, drop off, repeat', description: 'Drive your taxi around the city grid. Pick up passengers and deliver them to their destinations before the meter runs out.', category: 'action', icon: 'CarTaxiFront', accent: '#facc15', difficulty: 'Medium', controls: ['Arrow Keys', 'WASD'], featured: true },
  { slug: 'reflex-lights', title: 'Reflex Lights', tagline: 'Floor it when the light goes green', description: 'Wait for the green light and slam the gas as fast as you can. Your reaction time in milliseconds becomes your score — lower is better.', category: 'skill', icon: 'TrafficCone', accent: '#22c55e', difficulty: 'Easy', controls: ['Space / Click'] },
  { slug: 'fuel-run', title: 'Fuel Run', tagline: 'Collect fuel, dodge cones', description: 'Your tank is always draining. Grab fuel cans to refuel and dodge traffic cones. Run dry and the engine stops for good.', category: 'action', icon: 'Fuel', accent: '#06b6d4', difficulty: 'Medium', controls: ['Arrow Keys', 'A / D'] },
  { slug: 'drag-reaction', title: 'Drag Reaction', tagline: 'Perfect launch wins the race', description: 'Three... two... one... GO! Time your launch perfectly for the best reaction time. Too early and you false-start.', category: 'skill', icon: 'Flag', accent: '#a855f7', difficulty: 'Easy', controls: ['Space / Click'] },
  { slug: 'car-memory', title: 'Car Memory', tagline: 'Match the hidden car pairs', description: 'Flip cards to find matching car brand pairs. Clear the board in as few moves as possible — fewer moves means a higher score.', category: 'puzzle', icon: 'Brain', accent: '#10b981', difficulty: 'Easy', controls: ['Click / Tap'] },
  { slug: 'traffic-jam', title: 'Traffic Jam', tagline: 'Slide cars to clear the exit', description: 'Cars are gridlocked. Slide them horizontally and vertically to clear a path for the red car to reach the exit.', category: 'puzzle', icon: 'Grid3x3', accent: '#f43f5e', difficulty: 'Hard', controls: ['Drag cars'], featured: true },
  { slug: 'overtake', title: 'Overtake', tagline: 'Pass safely, don\'t crash', description: 'You\'re the fastest car on the road. Weave past slower traffic and overtake as many cars as possible without a collision.', category: 'racing', icon: 'Split', accent: '#0ea5e9', difficulty: 'Medium', controls: ['Arrow Keys', 'A / D'] },
  { slug: 'color-match-cars', title: 'Color Match Cars', tagline: 'Sort cars into matching lanes', description: 'Cars of different colors roll toward you. Switch them into the lane that matches their color before they pass the line.', category: 'puzzle', icon: 'Palette', accent: '#ec4899', difficulty: 'Easy', controls: ['Arrow Keys'] },
  { slug: 'road-maze', title: 'Road Maze', tagline: 'Navigate the car to the finish', description: 'Drive your car through a procedurally generated maze. Find the exit flag before the timer hits zero.', category: 'puzzle', icon: 'Navigation', accent: '#8b5cf6', difficulty: 'Medium', controls: ['Arrow Keys', 'WASD'] },
  { slug: 'wheel-spin', title: 'Wheel Spin', tagline: 'Stop the wheel on the jackpot', description: 'A tire spins faster and faster. Tap to stop it as close to the jackpot marker as you can. Closer means more points.', category: 'skill', icon: 'Disc3', accent: '#eab308', difficulty: 'Easy', controls: ['Space / Click'] },
  { slug: 'rally-countdown', title: 'Rally Countdown', tagline: 'Hit the gas at the right number', description: 'Count down from a target number and hit the gas when you reach zero. The closer you are, the more points you score.', category: 'skill', icon: 'Timer', accent: '#f59e0b', difficulty: 'Easy', controls: ['Space / Click'] },
  { slug: 'lane-weaver', title: 'Lane Weaver', tagline: 'Five lanes, infinite traffic', description: 'A five-lane freeway with cars coming at you from every direction. Switch lanes at the right moment to thread the needle.', category: 'racing', icon: 'GitBranch', accent: '#14b8a6', difficulty: 'Hard', controls: ['Arrow Keys', 'A / D'] },
  { slug: 'night-drive', title: 'Night Drive', tagline: 'Headlights reveal the road', description: 'Drive through the dark with only your headlights illuminating the road ahead. React to obstacles as they emerge from the shadows.', category: 'action', icon: 'Moon', accent: '#6366f1', difficulty: 'Medium', controls: ['Arrow Keys'], featured: true },
];
