import { useState } from 'react';
import { Heart, Coffee, Fuel, Zap, Star, Code, Palette, Github, Twitter, Mail, Check } from 'lucide-react';

const DONATION_TIERS = [
  { id: 'fuel', icon: Fuel, label: 'Tank of Gas', amount: 5, desc: 'Keeps the servers running for a day', color: '#06b6d4' },
  { id: 'coffee', icon: Coffee, label: 'Coffee Fund', amount: 10, desc: 'Fuel for the developer behind the wheel', color: '#f97316' },
  { id: 'boost', icon: Zap, label: 'Turbo Boost', amount: 25, desc: 'Helps build new games and features', color: '#a855f7' },
  { id: 'legend', icon: Star, label: 'Legend Status', amount: 50, desc: 'Your name on the credits wall forever', color: '#facc15' },
];

const CREDITS = [
  { role: 'Developer & Designer', name: 'Turbo Arcade Team', icon: Code, desc: 'Built all 16 games from scratch with React, TypeScript and the HTML Canvas API.' },
  { role: 'Photography', name: 'Pexels Contributors', icon: Palette, desc: 'Hero and section photography sourced from the Pexels free-stock library.' },
  { role: 'Tech Stack', name: 'Open Source', icon: Github, desc: 'React, Vite, Tailwind CSS, Lucide Icons, Supabase, and the Deno runtime.' },
];

export function DonatePage() {
  const [selected, setSelected] = useState('coffee');
  const [customAmount, setCustomAmount] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const handleDonate = (e: React.FormEvent) => { e.preventDefault(); setSubmitted(true); setTimeout(() => setSubmitted(false), 4000); };
  const amount = customAmount || DONATION_TIERS.find((t) => t.id === selected)?.amount.toString() || '';

  return (
    <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6">
      <div className="text-center"><span className="inline-flex items-center gap-2 rounded-full bg-accent-100 px-4 py-1.5 text-sm font-semibold text-accent-700 dark:bg-accent-500/15 dark:text-accent-400"><Heart className="h-4 w-4 fill-current" /> Support the arcade</span><h1 className="mt-4 font-display text-4xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-5xl">Donate & Credits</h1><p className="mx-auto mt-4 max-w-2xl text-lg text-slate-600 dark:text-slate-400">Turbo Arcade is free to play, forever. Donations keep the servers running, fund new games, and keep the developer caffeinated. Every bit helps.</p></div>
      <section className="mt-12 grid gap-6 lg:grid-cols-[1fr_380px]">
        <div className="space-y-4"><h2 className="font-display text-xl font-bold text-slate-900 dark:text-white">Choose a donation tier</h2><div className="grid gap-3 sm:grid-cols-2">{DONATION_TIERS.map((tier) => { const Icon = tier.icon; const active = selected === tier.id && !customAmount; return (<button key={tier.id} onClick={() => { setSelected(tier.id); setCustomAmount(''); }} className={`group relative flex items-start gap-4 rounded-2xl border-2 p-4 text-left transition-all ${active ? 'border-brand-500 bg-brand-50 dark:bg-brand-500/10' : 'border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600'}`}><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-white shadow-md transition-transform group-hover:scale-110" style={{ backgroundColor: tier.color }}><Icon className="h-5 w-5" /></div><div className="flex-1"><div className="flex items-center justify-between"><span className="font-display font-bold text-slate-900 dark:text-white">{tier.label}</span><span className="font-display text-lg font-bold text-brand-600 dark:text-brand-400">${tier.amount}</span></div><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{tier.desc}</p></div>{active && <span className="absolute right-3 top-3 flex h-5 w-5 items-center justify-center rounded-full bg-brand-500 text-white"><Check className="h-3 w-3" /></span>}</button>); })}</div><div className="rounded-2xl border border-slate-200 dark:border-slate-700/60 p-4"><label className="block"><span className="text-sm font-semibold text-slate-700 dark:text-slate-300">Or enter a custom amount</span><div className="mt-2 relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-lg font-bold text-slate-400">$</span><input type="number" min={1} value={customAmount} onChange={(e) => setCustomAmount(e.target.value)} placeholder="0" onFocus={() => setSelected('')} className="input pl-8 text-lg font-semibold" /></div></label></div></div>
        <div className="lg:sticky lg:top-24 lg:self-start"><div className="card overflow-hidden"><div className="bg-gradient-to-br from-brand-600 to-accent-500 p-6 text-white"><p className="text-sm font-semibold uppercase tracking-wider opacity-80">You're donating</p><p className="mt-1 font-display text-4xl font-bold">${amount || '0'}<span className="text-lg font-normal opacity-80"> USD</span></p></div><div className="p-6"><form onSubmit={handleDonate} className="space-y-4"><label className="block"><span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Email (for receipt)</span><input type="email" required placeholder="you@example.com" className="input mt-1.5" /></label><label className="block"><span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Leave a message (optional)</span><textarea placeholder="Thanks for the games!" rows={2} className="input mt-1.5 resize-none" /></label><button type="submit" disabled={submitted || !amount || Number(amount) <= 0} className="btn-accent w-full text-base">{submitted ? <><Check className="h-5 w-5" /> Thank you!</> : <><Heart className="h-5 w-5 fill-current" /> Donate ${amount || '0'}</>}</button><p className="text-center text-xs text-slate-400">This is a demo donation form — no payment is processed.</p></form></div></div></div>
      </section>
      <section className="mt-16"><h2 className="font-display text-xl font-bold text-slate-900 dark:text-white">Where your donation goes</h2><div className="mt-4 grid gap-4 sm:grid-cols-3">{[{ icon: Fuel, title: 'Servers', desc: 'Hosting, database, and global CDN costs to keep games loading fast.' }, { icon: Code, title: 'New Games', desc: 'Time and tools to build more car games and polish existing ones.' }, { icon: Coffee, title: 'Caffeine', desc: 'The developer runs on coffee. Enough said.' }].map((item) => { const Icon = item.icon; return (<div key={item.title} className="card p-5"><Icon className="h-6 w-6 text-brand-500" /><h3 className="mt-3 font-display font-bold text-slate-900 dark:text-white">{item.title}</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{item.desc}</p></div>); })}</div></section>
      <section className="mt-16"><div className="rounded-2xl border border-slate-200 dark:border-slate-700/60 bg-gradient-to-br from-slate-50 to-white dark:from-slate-800/40 dark:to-slate-900/40 p-6 sm:p-8"><h2 className="font-display text-2xl font-bold text-slate-900 dark:text-white">Credits</h2><p className="mt-2 text-slate-500 dark:text-slate-400">Turbo Arcade wouldn't exist without these people and projects.</p><div className="mt-6 space-y-4">{CREDITS.map((c) => { const Icon = c.icon; return (<div key={c.role} className="flex flex-col gap-3 rounded-xl border border-slate-200 dark:border-slate-700/60 bg-white dark:bg-slate-800/60 p-4 sm:flex-row sm:items-center"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-100 text-brand-600 dark:bg-brand-500/15 dark:text-brand-400"><Icon className="h-5 w-5" /></div><div className="flex-1"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{c.role}</p><p className="font-display font-bold text-slate-900 dark:text-white">{c.name}</p><p className="mt-0.5 text-sm text-slate-500 dark:text-slate-400">{c.desc}</p></div></div>); })}</div><div className="mt-8 flex flex-wrap items-center gap-3"><span className="text-sm font-semibold text-slate-500 dark:text-slate-400">Follow:</span>{[{ icon: Github, label: 'GitHub' }, { icon: Twitter, label: 'Twitter' }, { icon: Mail, label: 'Email' }].map((s) => { const Icon = s.icon; return (<button key={s.label} className="flex items-center gap-2 rounded-lg border border-slate-200 dark:border-slate-700 px-3 py-1.5 text-sm font-semibold text-slate-600 transition hover:border-brand-400 hover:text-brand-600 dark:text-slate-300 dark:hover:text-brand-400"><Icon className="h-4 w-4" /> {s.label}</button>); })}</div></div></section>
    </div>
  );
}
